name: Python Test

on:
    schedule:
      - cron: '0 4,16 * * *'  # Run at 12 AM ET and 12 PM ET
    push:
      branches:
        - main
        - development  # Add the second branch you want to monitor

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Choose the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest test/

      - name: Run Black
        run: black *.py

      - name: Run Pylint
        run: pylint --disable=R,C,E1120 *.py
        continue-on-error: true  # Allows the workflow to continue even if pylint returns non-zero

      - name: Display Pylint results
        run: cat pylint.log         
        
        

